### ISSUE TITLE
Use github actions?

### ISSUE THREAD

**Issue by kt86** [kainagel/freight-dfg17#33]
Should we try to setup githup actions for CI?

We have switch matsim-libs to it and I think some other projects as well... 
As far as I have seen in #32 there is no CI check at the moment working for this repo (before it was travis)

**Comment by JWJoubert** [comment]
Hi @kt86. Similar to the rest of MATSim, using pull-requests?

Maybe it also depends on what the status is of DFG's approval on whether this can become public. We (@wlbean and I) are slowly starting to get the Receiver class(es) ready to move into a) a separate contribution, or b) merge it into the `freight` contrib.

**Comment by kt86** [comment]
Hi @JWJoubert 

yes, a bit as it is in MATSim.
But here I would **not** do all the builds for having PullRequest-based builds available.

I would like to focus on a working CI testing, that will check i) branches after a push and ii) Pull requests.

--> In the end, it could (should?) go (again) in the direction that one uses PRs to merge things into the master to ensure a having a master with passing tests.
